# Generated by Django 5.2.1 on 2025-05-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iscrizione_esame_corso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_studente', models.IntegerField()),
                ('id_corso', models.IntegerField()),
                ('id_esame', models.IntegerField()),
            ],
        ),
    ]
