# Generated by Django 5.2.1 on 2025-05-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esame',
            name='description',
            field=models.TextField(default=-1),
            preserve_default=False,
        ),
    ]
