# Generated by Django 5.2.1 on 2025-05-14 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corso',
            name='id_category',
        ),
    ]
