# Generated by Django 5.2.1 on 2025-05-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
