# Generated by Django 5.2.1 on 2025-05-14 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risultato_esame_corso', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risultato_esame_corso',
            old_name='id_esame',
            new_name='id_corso',
        ),
    ]
